#!/usr/bin/env bash

# This file needs lots of refactoring

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source link${COLOR_NC}\n\n"
fi

rm ~/.bash_profile
rm ~/.bashrc
rm ~/.bashrc_help
rm ~/.bashrc_app_specific

ln -s ~/projects/dotfiles/etc/bash_profile ~/.bash_profile
ln -s ~/projects/dotfiles/etc/bashrc ~/.bashrc
ln -s ~/projects/dotfiles/etc/bashrc_help ~/.bashrc_help
ln -s ~/projects/dotfiles/etc/bashrc_app_specific ~/.bashrc_app_specific

# vim
rm ~/.vimrc
rm ~/.gvimrc
rm ~/.vim

ln -s ~/projects/dotfiles/etc/vim/vimrc ~/.vimrc
ln -s ~/projects/dotfiles/etc/vim/gvimrc ~/.gvimrc
ln -s ~/projects/dotfiles/etc/vim ~/.vim

# netbeans
#rm ~/.netbeans/6.0/config
#ln -s ~/projects/dotfiles/etc/netbeans/6.0/config ~/.netbeans/6.0/config

# subversion
rm ~/.subversion
ln -s ~/projects/dotfiles/etc/subversion ~/.subversion

# autotest
rm ~/.autotest
ln -s ~/projects/dotfiles/etc/autotest ~/.autotest

# irb
rm ~/.irbrc
ln -s ~/projects/dotfiles/etc/irbrc ~/.irbrc

# git
rm ~/.gitconfig
rm ~/.gitignore
rm ~/.gitattributes
ln -s ~/projects/dotfiles/etc/gitconfig ~/.gitconfig
ln -s ~/projects/dotfiles/etc/gitignore ~/.gitignore
ln -s ~/projects/dotfiles/etc/gitattributes ~/.gitattributes

# add symbolic link just in case some configs assume that things are under ~/cl
ln -s ~/projects/dotfiles cl

# make backup directory so that vim will work as set in vimrc
mkdir ~/backup
mkdir ~/backup/vim
mkdir ~/backup/vim/swap



source ~/.bash_profile
