#!/usr/bin/env bash

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source ./link${COLOR_NC}"
else

  link (){
    if [ -e $1 ]; then
      if [ -e $2 ]; then
        rm $2
      fi

      ln -s $1 $2
    fi
  }

  # bash
  link ~/projects/dotfiles/etc/bash_profile ~/.bash_profile
  link ~/projects/dotfiles/etc/bashrc ~/.bashrc
  link ~/projects/dotfiles/etc/bashrc_help ~/.bashrc_help
  link ~/projects/dotfiles/etc/bashrc_app_specific ~/.bashrc_app_specific
  
  # vim
  link ~/projects/dotfiles/etc/vim/vimrc ~/.vimrc
  link ~/projects/dotfiles/etc/vim/gvimrc ~/.gvimrc
  link ~/projects/dotfiles/etc/vim ~/.vim
  
  # git
  link ~/projects/dotfiles/etc/gitconfig ~/.gitconfig
  link ~/projects/dotfiles/etc/gitignore ~/.gitignore
  link ~/projects/dotfiles/etc/gitattributes ~/.gitattributes
  
  # misc
  link ~/projects/dotfiles/etc/subversion ~/.subversion
  link ~/projects/dotfiles/etc/autotest ~/.autotest
  link ~/projects/dotfiles/etc/irbrc ~/.irbrc
  link ~/projects/dotfiles/etc/ssh_config ~/.ssh/config
  
  # irb
  #link ~/projects/dotfiles/etc/irbrc ~/.irbrc
  

  # make backup directory so that vim will work as set in vimrc
  mkdir ~/backup
  mkdir ~/backup/vim
  mkdir ~/backup/vim/swap

  # add symbolic link just in case some configs assume that things are under ~/cl
  ln -s ~/projects/dotfiles ~/cl
  
  source ~/.bash_profile

fi
